### ISSUE TITLE
Possible to run without "--harmony --use_strict" ?

### ISSUE THREAD

**Issue by drschwabe** [edwellbrook/node-tvdb#11]
Hi there, with this module I can only run my app using ```node --harmony --use_strict myApp.js``` is there a way to get node-tvdb working without those flags?  Unfortunately other modules in my project have issues with those.

**Comment by edwellbrook** [comment]
Hey, thanks for getting in touch. Which version of node are you using?

**Comment by drschwabe** [comment]
node 12.7 without flags returns: 
```
$ node myapp
/myapp/node_modules/node-tvdb/index.js:12
const request = require("request");
^^^^^
SyntaxError: Use of const in strict mode.
...
```
If you add --harmony it results in a slightly different error: 
```
$ node --harmony myapp
/myapp/node_modules/node-tvdb/index.js:41
class Client {
^^^^^
SyntaxError: Unexpected reserved word
```
And finally, with --harmony and --use_strict flags no errors but then a dozen other of my modules throw errors :/

**Comment by edwellbrook** [comment]
if you `require('node-tvdb/compat')` does this fix the issue?

**Comment by edwellbrook** [comment]
(see second piece of example code in example usage in readme for more info)

**Comment by drschwabe** [comment]
Ah, yes requiring ```node-tvdb/compat`` does solve it; didn't see that second example there, thank-you.

**Comment by edwellbrook** [comment]
glad to hear its all working now! let me know if you run into any other issues. thanks!
