### ISSUE TITLE
Search filtered by year

### ISSUE THREAD

**Issue by ocombe** [edwellbrook/node-tvdb#24]
Hello,

is this possible to add the search param "year" as specified in [the API](http://docs.trakt.apiary.io/reference/search) ?
> You can optionally limit the type of results to return. Send a comma separated string to get results for multiple types. You can optionally filter the **year** for movie and show results.

**Comment by ocombe** [comment]
Woops wrong repo :D sorry about that

**Comment by edwellbrook** [comment]
haha no worries!

**Comment by ocombe** [comment]
that's what happens when you have so many tabs opened :-/

**Comment by edwellbrook** [comment]
Sadly that's not an issue I can fix :stuck_out_tongue_winking_eye: 

If you do end up using this project though, let me know if I can help you at all! :)

**Comment by ocombe** [comment]
Well I started using it, but the TVdb is so slow (not your fault though) :(
I'm trying [Trackt](https://trakt.tv/), they have a nice api (with no limitation) and basically have everything from the tvdb (which is probably their original source for content), but the API answers a lot faster !
http://docs.trakt.apiary.io/

**Comment by edwellbrook** [comment]
Ah that makes sense! Just in case you're interested, the TVDB are working on releasing v2 of their api, and it seems to be a lot better: https://api-beta.thetvdb.com/swagger

Not sure if its any faster than Trakt's though. Some work has started on updating this project for it in a new branch, in case you're interested in contributing :)

**Comment by ocombe** [comment]
Ah that looks nice, the xml was sooo 2000 :D
I'll stay on trakt for now, but thanks anyway
