### ISSUE TITLE
mirrors?

### ISSUE THREAD

**Issue by mark-hahn** [edwellbrook/node-tvdb#27]
I need to get a URL to retrieve the banners.  I assume I need to get the mirrors list and pick one.  How do I do this?

**Comment by edwellbrook** [comment]
Hey, really sorry it's not clear.

The `tvdb.getBanners` method will return an array of objects of this format (as I'm sure you've discovered):

```js
{
    id: '74141',
    BannerPath: 'fanart/original/73255-33.jpg',
    BannerType: 'fanart',
    BannerType2: '1280x720',
    Colors: '|57,57,57|27,17,15|48,31,23|',
    Language: 'en',
    Rating: '6.8636',
    RatingCount: '22',
    SeriesName: 'false',
    ThumbnailPath: '_cache/fanart/original/73255-33.jpg',
    VignettePath: 'fanart/vignette/73255-33.jpg'
}
```

The `BannerPath` key should be appended to "http://thetvdb.com/banners/", so the above example will be "http://thetvdb.com/banners/fanart/original/73255-33.jpg".

TheTVDB doesn't provide a list of mirrors for the banners as far as I know, so I will likely add in the base url there by default in the future.

Hope this clears things up and answers your question.

**Comment by mark-hahn** [comment]
I just noticed the getBanners call.  I was used to another library that had a getMirrors call.

Anyway, now I can't get the getBanners call to work.  Here is my call and the result ...


```
tvdb.getBanners id, (err, res) ->
  console.log 'getBanners', {id, err, res}

tvdb: getBanners { id: '269593',
  err: { [Error: Could not complete the request] statusCode: 404 },
  res: undefined }
```

I got the id from here ...

```
  tvdb.getSeriesByName name, (err, res) ->
    console.log res

   [ { seriesid: '269593',
       language: 'en',
       SeriesName: 'About a Boy',
       banner: 'graphical/269593-g7.jpg',
       Overview: 'Based on the best-selling Nick Hornby novel, written/produced by Jason Katims and directed by Jon Favreau comes a different kind of coming-of-age story. Will Freeman lives a charmed existence as the ultimate man-child. After writing a hit song, he was granted a life of free time, free love and freedom from financial woes. He’s single, unemployed and loving it. So imagine his surprise when Fiona, a needy, single mom and her oddly charming 11-year-old son Marcus move in next door and disrupt his perfect world.',
       FirstAired: '2014-02-22',
       Network: 'NBC',
       IMDB_ID: 'tt2666270',
       zap2it_id: 'EP01738426',
       id: '269593' } ] }
```

I'll try to trace through the code.  Thanks in advance...

**Comment by mark-hahn** [comment]
I sent that before I got your reply.  Thanks.  I'll try to trace down the 404.

**Comment by edwellbrook** [comment]
oh, that's really odd. seems to work fine for me running:

```js
tvdb.getBanners('269593', function(err, res) {})
```

Do let me know how you get on.

**Comment by mark-hahn** [comment]
I found the problem.  In compat/index/getBanners @token had a value of `2C92771D87CA8718"`.  Note the extra quote.

However, the banners result from tvdb was an empty array when using your sample id.  I'll continue to beat on this.

**Comment by edwellbrook** [comment]
The sample id you're using (`74141`) is the id for the banner image. The id for the series in that example is `73255`.

That looks like it might be your api key (edited comment above for you). Perhaps there was an error on your end when initialising the library?

**Comment by mark-hahn** [comment]
Hah!  Sorry.  The quote was from my code.  I don't know how getSeriesByName worked.  

Weird.  I'll continue to chase this.  Sorry to bother you so much.

**Comment by mark-hahn** [comment]
Everything is working.  Thanks again and again I'm sorry I bothered you.

**Comment by edwellbrook** [comment]
Not at all! Thanks for reaching out. Really happy I could help!

**Comment by edwellbrook** [comment]
Also, in case you're curious, the reason `getSeriesByName` worked was because it doesn't need or use an API key :)

**Comment by mark-hahn** [comment]
Aha.  That gave me the false idea that I had the key right.  By the time I'm done I'll be an expert on your code.  Maybe I can contribute something someday. :-)

**Comment by edwellbrook** [comment]
Sorry that wasn't clear either! Please do. If there's anything that could be done to make things clearer for you, please open an issue or pull request with some suggestions :)

**Comment by mark-hahn** [comment]
A quick question.  Do you know why the getTime call is there?  When would it be useful?

**Comment by edwellbrook** [comment]
Not needed for most use cases, but theres an example of its use here (see initial database processing section)

http://thetvdb.com/wiki/index.php/Programmers_API

**Comment by mark-hahn** [comment]
I'm sorry to be a pain but I can't find other url headers like "http://thetvdb.com/banners/".  I looked in the tvdb wiki with no luck.

I specifically need it for `episode.filename` (episodes/269593/4570034.jpg), which I assume is the episode thumbnail, and `actor.Image` (actors/326286.jpg).

I tried http://thetvdb.com/episodes/269593/4570034.jpg and http://thetvdb.com/actors/326286.jpg and got 404s.

-

**Comment by edwellbrook** [comment]
No worries. You want to use `"http://thetvdb.com/banners/" + banner` where `banner` is something like `"episodes/269593/4570034.jpg"`.

Those urls do not work, but http://thetvdb.com/banners/episodes/269593/4570034.jpg, for example does. Notice the entirety of "http://thetvdb.com/banners/" is in the url used.

Hope this clarifies things!

**Comment by mark-hahn** [comment]
Thanks.  I didn't think to try that.
