### ISSUE TITLE
question : path base??

### ISSUE THREAD

**Issue by smolleyes** [edwellbrook/node-tvdb#4]
hi

first thanks for this great api (and thetvdb is a great website too...) nice discovery...

just a stupid question since everything seems to work fine :p...

what s the base path of your links ? 

exemple 

fanart: "fanart/original/247897-27.jpg"

http://xxxxxx/fanart/original/247897-27.jpg

same thing for getBanners method etc... 

thanks !

**Comment by smolleyes** [comment]
ok seems to be http://thetvdb.com/banners :p

thanks !

**Comment by edwellbrook** [comment]
@smolleyes Would you like this worked into the module? So it returns the full url instead of just the path?

**Comment by smolleyes** [comment]
hello 

not a problem for for me but it could be a good idear to give the information in the getBanner exemple for exemple :) 

will post again if i have a problem or i ll send a PR if i add something :p

thanks

**Comment by edwellbrook** [comment]
@smolleyes Awesome, thanks! Will be adding example responses to the readme soon to help out with that and debugging. Would love to see what you come up with!
