### ISSUE TITLE
When will node-tvdb start using the new TVDB API?

### ISSUE THREAD

**Issue by yvanavermaet** [edwellbrook/node-tvdb#55]
Hi

I've noticed that this module uses the XML api of TheTVDB and that you started working on a version that uses the JSON api of TheTVDB (branch: new-tvdb-api).
Any idea if you're going to change the implementation and when this version would be released?

API documentation of the new version: https://api.thetvdb.com/swagger

Thanks in advance.

Kind regards,
Yannick

**Comment by edwellbrook** [comment]
Hey! Work on the `new-tvdb-api` branch started a while ago when the new API was still in beta. The intention was to finish it off when the API was finished, which it appears it now is.

- I think now would be a sensible time to start working on the `new-tvdb-api` branch again.
- The plan is to update this project for the new api, and do a major version bump.
- There is no ETA on when a new version will be released.

It would be great if you could help contribute to the `new-tvdb-api` branch to speed things along. Please let me know if you have any questions getting started :)

Cheers!

**Comment by edwellbrook** [comment]
Just created a new issue (https://github.com/edwellbrook/node-tvdb/issues/56) for updating the package to use the new API.
