### ISSUE TITLE
Update to use the new TVDB API

### ISSUE THREAD

**Issue by edwellbrook** [edwellbrook/node-tvdb#56]
- The new TVDB JSON API is finalised and public
- API documentation of the new version: https://api.thetvdb.com/swagger
- Existing branch with old work: `new-tvdb-api`

Will require a major version bump when publishing to npm.

**Comment by palortoff** [comment]
I've started reimplementing against the new API. Might take a while...

There will be huge breaking changes.
Most property names have changed.

I think it would be best to support both APIs as long as the old one is up and running.

**Comment by edwellbrook** [comment]
Heya, thanks for starting on this work. Please feel free to submit pull requests to the `new-tvdb-api` branch so others can help as well. I believe @yvanavermaet is also working on updating for the new API.

Breaking changes and updated property names are fine IMO if we:
 - release the package strictly targeting a version of the new API
 - always return an expected format for each call which is documented in the README/docs
 - bump to a new major version when we publish to npm

Happy to support both APIs simultaneously while the new client is in development, but once we're happy with it I'd like to only support the new client. People wanting to use the old client can target an older version of the package on npm, and transition to the new client at their own pace.

Let me know what you think 😃

**Comment by palortoff** [comment]
OK, API 2.0 only it is.
Definitely makes things easier :-)
I don't think we need to keep the old API during development. It will be on another branch until release anyway...

I did not start using the `new-tvdb-api` branch, as it is over a year old. I branched from master and started from scratch.
I'll probably have something worth pushing tonight. If you create a new branch from the current master I'll make a pull request to it.

Do you think we can retire the callback API? Supporting only the promise API is sufficient in my opinion.

**Comment by edwellbrook** [comment]
Sorry yes, I meant support them simultaneously in separate branches. One branch only targets old API (`master`) and one targets new API (`new-tvdb-api`).

Happy for you to have branched off of master, but could we still have pull requests (even if there are merge conflicts) directed at the `new-tvdb-api` branch. I'm also more than happy to overwrite the existing branch with your work and help get it into the repo. Looking forward to your PR so myself and others can work alongside you!

Keen to remove either callback or promises, as I think having both is perhaps a little overkill. If your pull request only offers promises that's fine; if you want to support both for the time being, and submit a PR for the removal of the callback API that's fine as well — your choice. :)

**Comment by edwellbrook** [comment]
@palortoff Thanks again, so much for your help on getting this out. Sorry for how long it's taken 😅
