### ISSUE TITLE
Avoid new login for every API call

### ISSUE THREAD

**Issue by palortoff** [edwellbrook/node-tvdb#64]
With the current implementation in new-tv-api for every api call a login request is performed.

@edwellbrook: Is there a reason, you removed the solution to this with 1118adcbdbbae4a5e708a3c579207e8f9178d3f0?

Prior to 1118adcbdbbae4a5e708a3c579207e8f9178d3f0 when constructing the client a login would be performed asynchronously. The login call was stored in the loginPromise.

Every subsequent call to the api would then use the authentication token returned by the loginPromise to authenticate.

**Comment by edwellbrook** [comment]
Just doing a little refactoring. It'll be resolved before merging into master. There're a couple `TODO` comments there. Would rather store the bearer token as a class variable and have it a little more transparent than the way it was previously implemented.

Planning to have it authenticate on the first API call and then just reuse the bearer token. Will keep working on things and happy for you to have a review of the changes before it's merged into master.

Hope this clears things up for you!

**Comment by palortoff** [comment]
This is what I tried at first as well. I don't think there is a good solution in an asynchronous environment. We need to cover the case where a second API call is triggered before the login of the first is complete.

**Comment by edwellbrook** [comment]
Good point on this, reimplemented as a promise :)
