### ISSUE TITLE
ZIP for getSeriesAllById

### ISSUE THREAD

**Issue by watdafox** [edwellbrook/node-tvdb#7]
I would really love to have the hability to use the zip instead of the xml for `getSeriesAllById`.

Example for "The Big Bang Theory" Series with the 'fr' lang request: 238KB of xml, 47KB of zip.

**Comment by edwellbrook** [comment]
nice idea! would you like to be handling the zipped data yourself, or for the data to be unzipped by `node-tvdb` and then that data parsed and presented back to you?

**Comment by watdafox** [comment]
The way I see it, but that's me and my lazyness talking, it would be something like: 

1. User requests zip
2. (node-tvdb) Get localized zip
3. (node-tvdb) Unzip the xml file
4. (node-tvdb) Parse xml
5. (node-tvdb) return object
6. User gets readable data.series.episode

Basically the user could have the same response as getSeriesAllById, but would reduce brandwidth impact (and more local calculations/process). Benefit mostly to TVDB servers.

**Comment by edwellbrook** [comment]
yup, thought so. looking into this all now, and ideally that's how we'd want to do it. I'll take a look at this when i have some time, but please feel free to submit a PR if you want to :smile:

**Comment by watdafox** [comment]
I looked a little before submitting but simply looking at `fs.createWriteStream() -> .pipe(require('unzip')())` or `var pack = new AdmZip(zip) -> pack.extractAllToAsync(dir, true, function())` makes me itchy^^

**Comment by watdafox** [comment]
you're the real MVP

**Comment by edwellbrook** [comment]
:smile: should be updated on npm as v1.3.0 as well now!

**Comment by watdafox** [comment]
mmmh, I don't seem able to have it working.

in `responseOk(error, respo, data)`, the  `data` is undefined.

**Comment by edwellbrook** [comment]
can you give me some example code to reproduce?

**Comment by edwellbrook** [comment]
or whatever you used that caused the error :)

**Comment by watdafox** [comment]
```
                        var Client = require('node-tvdb');
                        var tvdb = new Client('5B757353E14FA17B', 'fr');
                        tvdb.getSeriesAllById('80379').then(function (localization) {
                               console.log(localization.Overview);
                        });
```

**Comment by watdafox** [comment]
got it !

**Comment by edwellbrook** [comment]
does this happen every time for you? worked fine first time for me (although i did spot a couple of other bugs)

**Comment by watdafox** [comment]
data is a buffer and you pass it to `responseOk()` that doesn't seem to take a buffer

**Comment by watdafox** [comment]
probably better, handle the buffer in `responseOk` with: 


```
if (data.toString().indexOf("404 Not Found") !== -1) return false;
```

or add something to check if it's a buffer or not.

**Comment by edwellbrook** [comment]
yep, writing a fix to handle buffers in `responseOk`

**Comment by watdafox** [comment]
imo you can just:

``` 
function responseOk(error, resp, data) {
    if (error) return false;
    if (resp.statusCode !== 200) return false;
    if (!data) return false;
    if (data === "") return false;
    if (data.toString().indexOf("404 Not Found") !== -1) return false;

    return true;
}
```

because even if it's not a buffer, it will work. And it won't error if no "data" is passed because of your `if (!data) return false`.

Not sure you have to check anything

**Comment by edwellbrook** [comment]
check my latest code. if it works, i'll update on npm :)

**Comment by watdafox** [comment]
works fine here, thanks

**Comment by edwellbrook** [comment]
v1.3.1 on npm. please let me know if this issue comes up again or if you come across anything else! :)

**Comment by watdafox** [comment]
so far I only use getAllSeriesById^^ but probably switching our image calls from trakt to tvdb as trakt is slower

**Comment by edwellbrook** [comment]
ah nice. awesome stuff :) do let me know if there's anything that you need/want improved when you do that!

**Comment by watdafox** [comment]
well, if you're into webapps in js, android apps, ios apps... we always can use an extra hand at git.popcorntime.io, don't hesitate to step by and say hello, or on the forums discuss.popcorntime.io
