### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by giacomocerquone** [edwellbrook/node-tvdb#87]
Hi, I was scrolling your website from my smartphone and I noticed you've got some issues with the position of some elements that make it unusable. What do you think to release the website publicly on a repo so I could make PR and fix stuff? Would be also a normal evolution considering the open source nature of the project itselft.
Hoping for a feedback. Thank you, Giacomo.

**Comment by edwellbrook** [comment]
Hey Giacomo! Thanks for opening this issue :)

The website (I'm assuming you're referring to https://edwellbrook.github.io/node-tvdb/), uses the contents of [`/docs`](https://github.com/edwellbrook/node-tvdb/tree/master/docs), and is built with [jsdoc](http://usejsdoc.org/) and my fork of the [minami theme](https://github.com/edwellbrook/minami).

If you'd like to submit a PR to fix the bugs you find, please open them on this repo [edwellbrook/minami](https://github.com/edwellbrook/minami). If you submit a PR I'll regenerate the `/docs` directory with your changes.

Please let me know if you need any help. Cheers!

**Comment by edwellbrook** [comment]
Thanks for your help. Just regenerated the docs with the new theme 👍
