### ISSUE TITLE
getSeriesAllById broken in compat mode

### ISSUE THREAD

**Issue by palortoff** [edwellbrook/node-tvdb#9]
Thanks for adding the zip mode!

Unfortunately, the zip mode does not seem to work in compat mode.
When calling getSeriesAllById I get 
`TypeError: undefined is not a function
  at responseOk (C:\hg\EpiNode\node_modules\node-tvdb\compat\index.js:299:14)`

as the `Buffer` class does not have an `indexOf` function.
When I remove line 299, it all works...

**Comment by edwellbrook** [comment]
Hey, thanks for the heads up on this issue. If data is a buffer, then it shouldnt reach the indexOf line in responseOk. The error seems to happen on line 299 which is "    if (!data) return false;". It's odd that it errors there.

Could you please provide some example code to reproduce this issue, so we can get it fixed as soon as possible! Thanks!

**Comment by palortoff** [comment]
You're right. 
Somehow I only had 1.3.0. Just retried with 1.3.2.
Works fine. 

Sorry about the confusion...

**Comment by edwellbrook** [comment]
Awesome. No worries at all! :smile:
