### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by hauptrolle** [edwellbrook/node-tvdb#98]
Hey,

I am trying to use your library in a vue.js project, but I keep getting this error:

`XMLHttpRequest cannot load https://api.thetvdb.com/login. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 405.`

Is there any way to fix this?

**Comment by hauptrolle** [comment]
Nevermind. I just build a node.js proxi for the api. That works. Thanks for this nice library 👍

**Comment by edwellbrook** [comment]
Glad you fixed your issue! :) You're welcome 😄
